// models/CjRating.js
'use strict';

const mongoose = require('mongoose');

const cjRatingSchema =
  new mongoose.Schema(
    {
      /*
       * This rating belongs only to a CJ product.
       *
       * It must never point to the internal Product model.
       */
      cjProduct: {
        type:
          mongoose.Schema.Types.ObjectId,

        ref: 'CjProduct',

        required: true,

        index: true,
      },

      /*
       * Keep the public CJ product identifier as a snapshot.
       *
       * This makes support, auditing and debugging easier,
       * while cjProduct remains the authoritative relation.
       */
      cjProductId: {
        type: String,

        required: true,

        trim: true,

        maxlength: 300,

        index: true,
      },

      /*
       * A rating may be submitted by:
       *
       * - a normal Kasyora user
       * - a Kasyora business account
       * - a guest browser identified by a secure cookie
       */
      raterType: {
        type: String,

        enum: [
          'user',
          'business',
          'guest',
        ],

        required: true,

        index: true,
      },

      raterUser: {
        type:
          mongoose.Schema.Types.ObjectId,

        ref: 'User',

        default: null,

        index: true,
      },

      raterBusiness: {
        type:
          mongoose.Schema.Types.ObjectId,

        ref: 'Business',

        default: null,

        index: true,
      },

      /*
       * Guest identity is generated by the CJ rating route
       * and stored in an HttpOnly cookie.
       */
      guestKey: {
        type: String,

        default: null,

        trim: true,

        maxlength: 200,

        index: true,
      },

      stars: {
        type: Number,

        required: true,

        min: 1,

        max: 5,
      },

      title: {
        type: String,

        trim: true,

        maxlength: 120,

        default: '',
      },

      body: {
        type: String,

        trim: true,

        maxlength: 2000,

        default: '',
      },

      status: {
        type: String,

        enum: [
          'published',
          'hidden',
          'flagged',
        ],

        default: 'published',

        index: true,
      },

      /*
       * Records who flagged the review.
       *
       * This remains optional because old reviews and
       * unflagged reviews do not require these fields.
       */
      flaggedByType: {
        type: String,

        enum: [
          'user',
          'business',
          null,
        ],

        default: null,
      },

      flaggedByUser: {
        type:
          mongoose.Schema.Types.ObjectId,

        ref: 'User',

        default: null,
      },

      flaggedByBusiness: {
        type:
          mongoose.Schema.Types.ObjectId,

        ref: 'Business',

        default: null,
      },

      flaggedAt: {
        type: Date,

        default: null,
      },
    },
    {
      timestamps: true,

      minimize: false,
    },
  );

/*
 * One CJ rating per authenticated USER
 * for each CJ product.
 */
cjRatingSchema.index(
  {
    cjProduct: 1,

    raterType: 1,

    raterUser: 1,
  },
  {
    unique: true,

    partialFilterExpression: {
      raterType: 'user',

      raterUser: {
        $type: 'objectId',
      },
    },
  },
);

/*
 * One CJ rating per authenticated BUSINESS
 * for each CJ product.
 */
cjRatingSchema.index(
  {
    cjProduct: 1,

    raterType: 1,

    raterBusiness: 1,
  },
  {
    unique: true,

    partialFilterExpression: {
      raterType: 'business',

      raterBusiness: {
        $type: 'objectId',
      },
    },
  },
);

/*
 * One CJ rating per GUEST browser
 * for each CJ product.
 */
cjRatingSchema.index(
  {
    cjProduct: 1,

    raterType: 1,

    guestKey: 1,
  },
  {
    unique: true,

    partialFilterExpression: {
      raterType: 'guest',

      guestKey: {
        $type: 'string',
      },
    },
  },
);

/*
 * Speeds up public review listings.
 */
cjRatingSchema.index({
  cjProduct: 1,

  status: 1,

  createdAt: -1,
});

/*
 * Speeds up support searches using the public CJ ID.
 */
cjRatingSchema.index({
  cjProductId: 1,

  status: 1,

  createdAt: -1,
});

module.exports =
  mongoose.models.CjRating ||
  mongoose.model(
    'CjRating',
    cjRatingSchema,
  );
